### ISSUE TITLE
How to redirect after info is logged in form

### ISSUE THREAD

**Issue by madhavalwadhi** [levinunnink/html-form-to-google-sheet#10]
Its working very well for me but after the form is submitted it just shows {"result":"success","row":1}

How would i get the page to redirect to another url after the form is submitted

Sorry if the answer is very obvious, im very new to coding

Thank you for your work

**Comment by levinunnink** [comment]
#11

**Comment by levinunnink** [comment]
If you're new to coding, I also recommend creating a free Sheet Monkey account: https://sheetmonkey.io/ which allows you do a redirect without any coding at all.
