### ISSUE TITLE
How do I use the provided code to interrupt and have the form redirect once submitted?

### ISSUE THREAD

**Issue by Afogle317** [levinunnink/html-form-to-google-sheet#11]
The code for this is working for me and my form submissions are going into the google sheet however I cannot figure out how to use the provided code to interrupt and have the form redirect once submitted.

**Comment by levinunnink** [comment]
This could possibly be accomplished with an AJAX form submission. https://www.digitalocean.com/community/tutorials/submitting-ajax-forms-with-jquery

```javascript

$(document).ready(function () {
  $("form").submit(function (event) {
    var formData = {
      name: $("#name").val(),
    };

    $.ajax({
      type: "POST",
      url: "<your-action-url>",
      data: formData,
      dataType: "json",
      encode: true,
    }).done(function (data) {
      window.location = '<your redirect>';
    });

    event.preventDefault();
  });
});

````

I haven't tested this method but it seems fairly straightforward.
