### ISSUE TITLE
Issue regarding saving the File Address when we put "File" as Input-Type

### ISSUE THREAD

**Issue by Ramneek-kalra** [levinunnink/html-form-to-google-sheet#2]
Hey! Thanks for developing such useful code. I am looking forward to your guidance, how we can get the file address once uploaded via HTML File input type. 

Looking forward to hearing from you.

**Comment by levinunnink** [comment]
Hi Ramneek, thanks for reaching out. The example doesn't actually handle file uploads. I'll see if I can figure out how to make that work. Looks like it's possible: https://stackoverflow.com/questions/31126181/uploading-multiple-files-to-google-drive-with-google-app-script

**Comment by levinunnink** [comment]
Duplicate of #8 Enhancement.
