### ISSUE TITLE
problem after submit

### ISSUE THREAD

**Issue by carloslencargorges** [levinunnink/html-form-to-google-sheet#3]
when I press submit I see this message:
```{"result":"error","error":{}}```

**Comment by Ramneek-kalra** [comment]
Hey, I am also new user to this repo project, may I know the output you're getting into inspect window when you pressed submit?

**Comment by levinunnink** [comment]
Hmm. Can you post example of the HTML code that you're using to submit?

**Comment by abdohwebdev** [comment]
same here 

`<form 
  method="POST" 
  action="https://script.google.com/macros/s/AKfycbw8QzcqXLrg2CjRclFm3s5WVRG7a2uYshRCjyc1JivqWW0mrhM-I8n3mX118yj85fw/exec"
>
  <input name="email" type="email" placeholder="Email" required>
  <button type="submit">Send</button>
</form>`

**Comment by abdohwebdev** [comment]
same here

**Comment by SEOSumit** [comment]
This is actually submitting the form but redirecting the to the scrip. Google URL. Is there any way to fix it? if js then explain how and where to put it?

Thanks in Advance.

**Comment by ShoneUnity** [comment]
Hi I had a problem here, I have followed all the tutorial and according to me it should work perfectly but when I click the submit button nothing happens, not even the Google screen comes, just the page is to be seen where i filled up the form and nothing is reflecting in the form.
I have copied the same code which is written here
<img width="1369" alt="Screenshot 2022-04-24 at 18 09 09" src="https://user-images.githubusercontent.com/74607492/164976976-9c0951b9-88c0-47fb-b5cb-1240b1de96a8.png">
<img width="1366" alt="Screenshot 2022-04-24 at 18 09 17" src="https://user-images.githubusercontent.com/74607492/164976982-3414cb02-40af-4eb1-b0ca-4a0f19ed4753.png">

`<form
      method : "POST"
      action : "https://script.google.com/macros/s/AKfycbwBX_cJC5avaNsdHv-pWAIt0EEHqtAC6XZBxEQWa6OjGutT78umU-NBsZZoMOkHkKYF/exec">
   </form>`

**Comment by Christopher-Force** [comment]
> > when I press submit I see this message: `{"result":"error","error":{}}`
> 
> 
> 
> same error here. Someone help me please :(

Please share your <form> code and your spreadsheet headers and I'll take a look

**Comment by Christopher-Force** [comment]
> Hi I had a problem here, I have followed all the tutorial and according to me it should work perfectly but when I click the submit button nothing happens, not even the Google screen comes, just the page is to be seen where i filled up the form and nothing is reflecting in the form.
> 
> I have copied the same code which is written here
> 
> <img width="1369" alt="Screenshot 2022-04-24 at 18 09 09" src="https://user-images.githubusercontent.com/74607492/164976976-9c0951b9-88c0-47fb-b5cb-1240b1de96a8.png">
> 
> <img width="1366" alt="Screenshot 2022-04-24 at 18 09 17" src="https://user-images.githubusercontent.com/74607492/164976982-3414cb02-40af-4eb1-b0ca-4a0f19ed4753.png">
> 
> 
> 
> `<form
> 
>       method : "POST"
> 
>       action : "https://script.google.com/macros/s/AKfycbwBX_cJC5avaNsdHv-pWAIt0EEHqtAC6XZBxEQWa6OjGutT78umU-NBsZZoMOkHkKYF/exec">
> 
>    </form>`
> 
> 

If you're still having issues, please send your entire form element with the input elements along with your spreadsheet headers and I'll take a look

**Comment by dih-vicenza** [comment]
> > > when I press submit I see this message: `{"result":"error","error":{}}`
> > 
> > 
> > same error here. Someone help me please :(
> 
> Please share your form code and your spreadsheet headers and I'll take a look


Ok @Christopher-Force !

The headers are: https://docs.google.com/spreadsheets/d/1NNn8Lxp0nBO7ngCwCJXkGKPT29k1pL2vQ3WK_O4_p5I/edit?usp=sharing

while the form code is:

<form 
  method="POST" 
 action="https://script.google.com/macros/s/AKfycbys401RD2C4sYkd4U6PYvsmeIqpJko6yNC3luI1F_9eohg5_ROVUTt_sEKHUy2eZ3sXOA/exec"
>
  <input name="Email" type="email" placeholder="Email" required>
  <input name="Name" type="text" placeholder="Name" required>
  <button type="submit">Send</button>
</form>

Thank you!

**Comment by Christopher-Force** [comment]
> > > > when I press submit I see this message: `{"result":"error","error":{}}`
> 
> > > 
> 
> > > 
> 
> > > same error here. Someone help me please :(
> 
> > 
> 
> > Please share your form code and your spreadsheet headers and I'll take a look
> 
> 
> 
> 
> 
> Ok @Christopher-Force !
> 
> 
> 
> The headers are: https://docs.google.com/spreadsheets/d/1NNn8Lxp0nBO7ngCwCJXkGKPT29k1pL2vQ3WK_O4_p5I/edit?usp=sharing
> 
> 
> 
> while the form code is:
> 
> 
> 
> <form 
> 
>   method="POST" 
> 
>  action="https://script.google.com/macros/s/AKfycbys401RD2C4sYkd4U6PYvsmeIqpJko6yNC3luI1F_9eohg5_ROVUTt_sEKHUy2eZ3sXOA/exec"
> 
> >
> 
>   <input name="Email" type="email" placeholder="Email" required>
> 
>   <input name="Name" type="text" placeholder="Name" required>
> 
>   <button type="submit">Send</button>
> 
> </form>
> 
> 
> 
> Thank you!
> 
> 

![image](https://user-images.githubusercontent.com/87559500/170303404-71abfe74-22d6-4184-8132-a6d1dc2f7baa.jpeg)

If you don't use this, your code will disappear 🙂

**Comment by dih-vicenza** [comment]
sorry @Christopher-Force, I'm a newby :)

`<form 
  method="POST" 
  action="https://script.google.com/macros/s/AKfycbys401RD2C4sYkd4U6PYvsmeIqpJko6yNC3luI1F_9eohg5_ROVUTt_sEKHUy2eZ3sXOA/exec"
>
  <input name="Email" type="email" placeholder="Email" required>
  <input name="Name" type="text" placeholder="Name" required>
  <button type="submit">Send</button>
</form>`

**Comment by Christopher-Force** [comment]
> sorry @Christopher-Force, I'm a newbie :)
> 
> 
> 
> `<form 
> 
>   method="POST" 
> 
>   action="https://script.google.com/macros/s/AKfycbys401RD2C4sYkd4U6PYvsmeIqpJko6yNC3luI1F_9eohg5_ROVUTt_sEKHUy2eZ3sXOA/exec"
> 
> >
> 
>   <input name="Email" type="email" placeholder="Email" required>
> 
>   <input name="Name" type="text" placeholder="Name" required>
> 
>   <button type="submit">Send</button>
> 
> </form>`

![image](https://user-images.githubusercontent.com/87559500/170317022-82d4785a-c079-4b1f-93a9-82a8b900df91.jpeg)

This is an old example of regular html implementation (Not a framework like React)

Each of your `name' attributes for your `<input>` elements must match case-sensitive to your headers, disregarding date.

The `id` attribute on `<form>` is only if you wish to stop the page from redirecting to a success screen, similar to what you saw for the error.

Let me know if this helps and if you have other questions!

-Chris

**Comment by shafeequekp** [comment]
ajax code for not to redirect to another page. means saving from same page not to go next page

**Comment by standa006** [comment]
hi a got a same issue 
`{"result":"error","error":{}}`
My form is
```

<form method="POST" action="https://script.google.com/macros/s/AKfycbw4Odn2kvRBVB_-xrx23l7SjpUrfhhsWgMGZJONjPCEj_fQshsadEKtieUA7sd6FIyc9w/exec">
  <input name="email" type="email" placeholder="email" required>
  <input name="name" type="text" placeholder="name" required>
  <button type="submit">Send</button>
</form>
```

and header in excel like 
![image](https://user-images.githubusercontent.com/81383208/171167374-cd2e3c26-fe3c-4602-b42f-9622a6e9eb8a.png)

Could you help me?

**Comment by luk1790** [comment]
@standa006 Check on code from step2 :
`const sheetName = 'Sheet1'` this name is the same like on your sheet
![image](https://user-images.githubusercontent.com/6923088/171860083-8773e7b8-3b4d-4ff3-8044-d7c6864c81d3.png)

**Comment by ExhausteDD** [comment]
> @standa006 Check on code from step2 : `const sheetName = 'Sheet1'` this name is the same like on your sheet ![image](https://user-images.githubusercontent.com/6923088/171860083-8773e7b8-3b4d-4ff3-8044-d7c6864c81d3.png)

I have same problem
Checked name of sheet, even naming sheet like in this example - still have {"result":"error","error":{}}

**Comment by ExhausteDD** [comment]
> hi a got a same issue `{"result":"error","error":{}}` My form is
> 
> ```
> 
> <form method="POST" action="https://script.google.com/macros/s/AKfycbw4Odn2kvRBVB_-xrx23l7SjpUrfhhsWgMGZJONjPCEj_fQshsadEKtieUA7sd6FIyc9w/exec">
>   <input name="email" type="email" placeholder="email" required>
>   <input name="name" type="text" placeholder="name" required>
>   <button type="submit">Send</button>
> </form>
> ```
> 
> and header in excel like ![image](https://user-images.githubusercontent.com/81383208/171167374-cd2e3c26-fe3c-4602-b42f-9622a6e9eb8a.png)
> 
> Could you help me?

Finaly i found what is the problem.
Here -> https://github.com/levinunnink/html-form-to-google-sheet#3-run-the-initialsetup-function you must set "doPost" instead of InitialSetup and it will work #4

**Comment by Keshy12** [comment]
If it's still not working for somebody:
Keep in mind that google uses your native language by default. Before doing the first intialSetup change the sheetName accordingly.
![image](https://user-images.githubusercontent.com/100865662/175807518-9b56044c-9105-406a-900c-f1f6b1e7cbbc.png)
Mine was "Arkusz1", I had to redo all of the steps with this change but after this it worked like a charm.

**Comment by rcuesta00** [comment]
Another mistake that maybe some people could be doing has to do with the Deployments.

Try to test first your deployment: Deploy > Test Deployment

Copy the URL to your HTML code (<form method="POST" action="URL_Test").

After testing, now you can do the Deploy as in the documentation. Otherwise, every time you change something in your script you has to do another deployment.

**Comment by ashloren** [comment]
How can I redirect those who submit the form to a URL on my site?

**Comment by Keshy12** [comment]
> How can I redirect those who submit the form to a URL on my site?

I'd try using AJAX to send POST request, and then redirect on success with jquery.

**Comment by erikantony** [comment]
It works great. How can I set that after form confirmation and sending will be reloaded new blank form? Thank you

**Comment by ff1st** [comment]
Mine worked perfectly well with the doPost. How do I redirect the form to another .html page, please, @Christopher-Force?

**Comment by ff1st** [comment]
> 

How do you do that?

**Comment by Christopher-Force** [comment]
> Mine worked perfectly well with the doPost. How do I redirect the form to another .html page, please, @Christopher-Force?

Sorry if my answer seems incomplete, in a rush and wanted to see if I could throw out some quick help.

This is a quick piece from an old project.
Written in ReactJS. Maybe use this to give a little guidance.

I imported useNavigate so that I'm able to change which page is routed. Highly recommend asking your questions to ChatGPT as they've already helped me code programs by myself that make my work life easier.
Prevent default stops the redirect, that's regular JS. After sending the data, I use the .then to insert my navigation function. You will have to use a different function if not using react.

import { useNavigate } from "react-router-dom";

  const subscribeToNewsLetter = (e) => {
    e.preventDefault();
    quoteButton.click();
    
    jsonp(`https://outlook.us5.list-manage.com/subscribe/post-json?xxxxx&${queryString.stringify(formValue)}`, { param: 'c' }, (err, data) => {
      console.log('err:', err);
      console.log('data:', data);
    }).then(navigate('/thankyou'));
  }

**Comment by wkpires** [comment]
Hey guys, I'm trying to do the same test (with external html), but restricting access to the domain and it's not working. With an html inside the google script it works.
![image](https://user-images.githubusercontent.com/11415665/223450099-5837eb3c-122a-4c8c-a8ee-b39ea60e8224.png)

**Comment by ff1st** [comment]
Hi, I'm sorry for late response. I'd like to know if you have found a way
around it yet to know if I am to send you the complete steps I took

**Comment by bbowers-hawaii** [comment]
I get
{"result":"error","error":{"name":"Exception"}}
if we have more headers than 3, do we edit the 
"const headers = sheet.getRange" line?

**Comment by Yuu-Rei** [comment]
Hi, I'm having this message: {"result":"success","row":2}
However only the date is reflected in the spreadsheets even after making sure that the form name values and spreadsheet headers have the same values.

Here is my html form code:
```
<form method="POST" 
                action="https://script.google.com/macros/s/AKfycbxnW2jlgzforWRNu0OOr3sw46qslhMXWwrzr0Mq8KVLk6Ndj3T89dSSci7C2CAUQdu1/exec"
                >
                <input name="name" type="text" placeholder="Name" class="box">
                <input name="email" type="email" placeholder="Email" class="box">
                <textarea name="message" id="" cols="30" rows="10" class="box message" placeholder="Message"></textarea>
                <button type="submit" class="btn"> Send <i class="fas fa-paper-plane"></i></button>
            </form>
```

![image](https://github.com/levinunnink/html-form-to-google-sheet/assets/140794705/d273d4e1-dd25-40dc-b7c4-7559b0f17009)

**Comment by tthompson0712** [comment]
Thanks for sharing.  I got everything working but I don't like the return page for success.  I then have to click the back button to go back to my website and the form is not reset.  Is there a way to automatically go back to the webpage after submit and auto reset form?  
![image](https://github.com/levinunnink/html-form-to-google-sheet/assets/143217767/ab19033a-7cd2-4c79-803c-f43a2eddd8d0)
![image](https://github.com/levinunnink/html-form-to-google-sheet/assets/143217767/b7431272-f88e-4905-a201-08f8021854d7)

**Comment by Keshy12** [comment]
> Thanks for sharing. I got everything working but I don't like the return page for success. I then have to click the back button to go back to my website and the form is not reset. Is there a way to automatically go back to the webpage after submit and auto reset form? ![image](https://private-user-images.githubusercontent.com/143217767/323696971-ab19033a-7cd2-4c79-803c-f43a2eddd8d0.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTM2MjEzOTksIm5iZiI6MTcxMzYyMTA5OSwicGF0aCI6Ii8xNDMyMTc3NjcvMzIzNjk2OTcxLWFiMTkwMzNhLTdjZDItNGM3OS04MDNjLWY0M2EyZWRkZDhkMC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNDIwJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDQyMFQxMzUxMzlaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT00Zjc5NjgyMTYzYzNhNjI5MWU2MDM4ZmJjZTI4MThiMGI5OWE0MjQzYTM3ZmY3NmQzZDFlZTI5YTdjZWEzYjliJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.lIfaAFGOJWFOfXMCiMqS3QXlgMu5xC3qnXLCG466hnI) ![image](https://private-user-images.githubusercontent.com/143217767/323697075-b7431272-f88e-4905-a201-08f8021854d7.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTM2MjEzOTksIm5iZiI6MTcxMzYyMTA5OSwicGF0aCI6Ii8xNDMyMTc3NjcvMzIzNjk3MDc1LWI3NDMxMjcyLWY4OGUtNDkwNS1hMjAxLTA4ZjgwMjE4NTRkNy5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNDIwJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDQyMFQxMzUxMzlaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1iNjJmZTMzYjVhZTA1ZDc3ZDEzOGU0ZTU0NTg1NDdkNGNmMzVhOWVkOGNkNzdjNWNlNzE0MmMwZTFhYTYyYTg4JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.0eBDlmFqD_IBryrjmklwUkxFeczgYxRPuR6vdru8izM)

Do it via AJAX, then you won't even need to redirect anywhere at all :)

**Comment by ff1st** [comment]
That is the only con I see about it, but I have stopped using the Google
sheet method, but instead, I use Php and Ajax
