### ISSUE TITLE
Sheet only generates timestamp not the test itself

### ISSUE THREAD

**Issue by Pro70Crazy** [levinunnink/html-form-to-google-sheet#5]
When I write any text, it only writes the timestamp every line not the text I wrote how?

**Comment by levinunnink** [comment]
Can you give an example of the form you created?

**Comment by MatthewKeracher** [comment]
Hi, I am not OP but have a question. I am using your code and adapting it as a way to have a live data connection between javascript and a google sheet. So far so good.

**Comment by Pro70Crazy** [comment]
Here i'm makng a question form. With no inout tag. I'm using the textarea tag. Is there a way to also use PHP 2 pages. 


HTML
`
<!DOCTYPE html>
<html>
  <head>
    <title>Questions</title>
    <link rel="stylesheet" href="/style.css">
  </head>
<body>
<h1>Questions</h1>
<form name="question" action="/questions/questions.php" method="post">

<h3>Ask a Question [BETA]</h3>

<textarea name="ask-question" rows=5 cols=25 placeholder="What are you doing?" id="display"></textarea><br />

<input type=submit value=Ask name=ask>
<br>
<p>NOTE: This is a beta version, if you clicked Ask after typing the question in field, the question is not sent. If you want to ask, you will need to ask via <a href="mailto:calvinbernardtanuri@gmail.com">Email</a> temporarily. you can help make this quick by sending me tips on how to send it to a spreadsheet, email, etc. via <a href="mailto:calvinbernardtanuri@gmail.com">Email</a>.</p>
</form>
  
  <a href="/">Go back home</a>
  <br>

<p>No Questions available yet!</p>
  <h2>Be the First to ask!</h2>
  <h3>Type the question in the text box then click Ask</h3>
  <a href="/faq.html">or go to FAQ</a>
</body>
</html>
`

PHP
`
<!DOCTYPE html>
<html>
<head>
<meta charset="utf-8">
<title>Thank You for your question</title>
<link rel="stylesheet" href="/style.css"
</head>
<body>
    <h1>Thank You</h1>
<p>You asked: <b><?php echo $_POST['ask-question'];

$Questions = $_POST['ask-question'];
$Timestamp = new DateTime();
?></b></p>
<br> <br>
<a href="index.html">Back to Questions</a>
<a href="/">Go back home</a>
 
</body>
 
</html>
`

**Comment by levinunnink** [comment]
@MatthewKeracher if you're still having issues can you open a separate issue?

@Pro70Crazy You can use this method on multiple pages but that requires you to build the HTML on the front-end.
