### ISSUE TITLE
Google Sheets Updated; Instructions Need Updating

### ISSUE THREAD

**Issue by cphaynes** [levinunnink/html-form-to-google-sheet#6]
** Context Only **
Instructions indicate going to Tools -> Script Editor. Google Sheets has been updated where the "Script Editor" is now "Extensions -> Apps Scripts". Otherwise, the script works as written.

**Comment by AcapSLP** [comment]
where is the "add triggers" button and modal now?

**Comment by levinunnink** [comment]
Thanks @cphaynes 

@AcapSLP same place. You just need to hover over the sidebar.
