### ISSUE TITLE
Works great but ...

### ISSUE THREAD

**Issue by vz-dave** [levinunnink/html-form-to-google-sheet#7]
I can get the data to populate the Sheet but when I try to preventDefault  and submit using the eventListener I get a CORS error. Any way around this?

Thanks for the assist!

**Comment by hdz-dev** [comment]
> Puedo obtener los datos para completar la hoja, pero cuando intento prevenir el valor predeterminado y enviarlos mediante eventListener, aparece un error de CORS. ¿Alguna forma de evitar esto?
> 
> ¡Gracias por la ayuda!

X2

**Comment by ignsm** [comment]
+1

**Comment by marquizzo** [comment]
I was having the same issue. I had to grant app access to "Anyone" for it to allow connections from any arbitrary URL, including my localhost dev environment:

1. Click on Deploy and 'Manage Deployments'
2. Edit the deployment
3. Who has access: Anyone.
4. Click Deploy

![updateAccess](https://user-images.githubusercontent.com/7864858/170799225-58117088-28d9-4938-b20b-e703840ba5aa.jpg)

**Comment by maicobernal** [comment]
Hello there.
Every time you change the code you should make a new deploy in order to see
tha changes.
I was having that issue also, i'm newbie ok GAS.
Cheers.

**Comment by levinunnink** [comment]
Thanks @maicobernal
