### ISSUE TITLE
Run very well but i have a issue with input checkbox

### ISSUE THREAD

**Issue by thiagoflaminio** [levinunnink/html-form-to-google-sheet#9]
**Describe the bug**

Hi man,
First i congrats, its a good job
My issue being with input checkbox, the app return me value for all input but don't checkboxes checked.
Can you help me please?

**To Reproduce**
My HTML :

` <input type="text" required="" name="nome" placeholder="Digite seu Nome aqui">
    <input type="number" pattern="^\d{11}$" required="" name="telefone" placeholder="DDD + Nº celular">
    <input type="e-mail" name="email" placeholder="Email (opcional)"><br><br>
    
        DIGITE SEU ENDEREÇO <input type="text" required="" name="endereço" placeholder="rua,nº,bairro cidade"><br>
    COPIE E COLE O ENDEREÇO DO MAPA <input type="url" name="end" placeholder="Localização (opcional)"><br><br>

    <label>HATCH <input type="checkbox" name="ch[]" value="60" /></label>
    <label>SEDAN <input type="checkbox" name="ch[]" value="60" /></label>
    <label>CROSSOVER <input type="checkbox" name="ch[]" value="60" /></label>
    <label>SUV <input type="checkbox" name="ch[]" value="60" /></label>
    <label>MINIVAN <input type="checkbox" name="ch[]" value="70" /></label>
    <label>PICUP <input type="checkbox" name="ch[]" value="70" /></label>
    <label>STATION WAGON <input type="checkbox" name="ch[]" value="70" /></label>
    <label>CONVERSÍVE <input type="checkbox" name="ch[]" value="70" /></label>
    <label>CUPE <input type="checkbox" name="ch[]" value="70" /></label>
    <label>LUXO <input type="checkbox" name="ch[]" value="70" /></label><br><br>
    
<p>ADICIONAIS</p><br>

	<label>LAVAGEM (SECO) DE MOTOR <input type="checkbox" name="ch[]" value="20" /></label>
	<label>CERA PLUS <input type="checkbox" name="ch[]" value="20" /></label>
	<label>CHEIRINHO <input type="checkbox" name="ch[]" value="10" /></label>
    

    <label>VALOR <input type="text" name="result" id="result" value="R$ 0,00" /></label><br>
    
    <button type="submit" value="ENVIAR">
    
</form>
</FONT>
</h2>

<script>
String.prototype.formatMoney = function() {
    var v = this;

    if(v.indexOf('.') === -1) {
        v = v.replace(/([\d]+)/, "$1,00");
    }

    v = v.replace(/([\d]+)\.([\d]{1})$/, "$1,$20");
    v = v.replace(/([\d]+)\.([\d]{2})$/, "$1,$2");
    v = v.replace(/([\d]+)([\d]{3}),([\d]{2})$/, "$1.$2,$3");

    return v;
};
String.prototype.toFloat = function() {
    var v = this;

    if (!v) return 0;
    return parseFloat(v.replace(/[\D]+/g, '' ).replace(/([\d]+)(\d{2})$/, "$1.$2"));
};
(function(){
    "use strict";

    var $chs = document.querySelectorAll('input[name="ch[]"]'),
        $result = document.getElementById('result'),
        chsArray = Array.prototype.slice.call($chs);

    chsArray.forEach(function(element, index, array){
        element.addEventListener("click", function(){
            var v = this.value,
                result = 0;
            v = v.toFloat();

            if (this.checked === true) {
                result = $result.value.toFloat() + parseFloat(v);
            } else {
                result = $result.value.toFloat() - parseFloat(v);
            }

            $result.value = "R$ " + String(result).formatMoney();
        });
    });

}());
</script>
`

**Expected behavior**

I just copy and past your code no change.
I need just checked boxs to appear in my sheets.

**Screenshots**
![image](https://user-images.githubusercontent.com/77864805/176058841-485d262b-126a-4727-9a18-e079962abcde.png)

![image](https://user-images.githubusercontent.com/77864805/176059107-25243161-922c-4546-ae9a-5ad8ba52be10.png)

**Desktop**

**Additional context**

The input name="result" dont appear in sheet too. 

Thanks again.

**Comment by levinunnink** [comment]
Make sure you have different names for the input fields. That could be causing the problem.
